"""
CSE 310 - Data Analysis Module

Project:
    E-Commerce Sales Analysis with Python and Pandas

Description:
    This program analyzes an e-commerce sales dataset.
    It answers three questions about the data:

    1. Which product categories generate the most revenue?
    2. Which regions have the highest average order value?
    3. Which products have the highest number of units sold?

    The program demonstrates:
    - Loading CSV data
    - Data conversion
    - Data cleaning
    - Filtering
    - Sorting
    - Grouping
    - Aggregation
    - Calculating averages
    - Calculating totals
    - Creating a graph with Matplotlib
"""

import os
import pandas as pd
import matplotlib.pyplot as plt


# File locations used by the program.
DATA_FILE = "data/global_ecommerce_sales.csv"
OUTPUT_DIRECTORY = "output"
CHART_FILE = os.path.join(OUTPUT_DIRECTORY, "sales_by_category.png")


def load_data(file_path):
    """
    Load the e-commerce CSV file into a Pandas DataFrame.

    Args:
        file_path: The path to the CSV dataset.

    Returns:
        A Pandas DataFrame containing the sales data.
    """
    print("\nLoading dataset...")

    try:
        data = pd.read_csv(file_path)
        print(f"Dataset loaded successfully: {len(data)} records.")
        return data
    except FileNotFoundError:
        print(f"Error: Could not find the file: {file_path}")
        return None


def clean_data(data):
    """
    Clean and prepare the dataset for analysis.

    This function converts the order date to a date type,
    removes duplicate records, creates a Revenue column,
    and removes rows containing invalid values.

    Args:
        data: The original Pandas DataFrame.

    Returns:
        A cleaned Pandas DataFrame.
    """
    print("\nCleaning data...")

    data = data.copy()

    # Convert Order_Date from text into a Pandas datetime value.
    data["Order_Date"] = pd.to_datetime(
        data["Order_Date"],
        errors="coerce"
    )

    # Convert numeric fields to numeric data types.
    data["Quantity"] = pd.to_numeric(
        data["Quantity"],
        errors="coerce"
    )

    data["Unit_Price"] = pd.to_numeric(
        data["Unit_Price"],
        errors="coerce"
    )

    # Calculate revenue for each order.
    data["Revenue"] = data["Quantity"] * data["Unit_Price"]

    # Remove duplicate records.
    before_duplicates = len(data)
    data = data.drop_duplicates()
    duplicates_removed = before_duplicates - len(data)

    # Remove rows that do not have the information needed for analysis.
    data = data.dropna(
        subset=[
            "Order_Date",
            "Region",
            "Product_Category",
            "Product_Name",
            "Quantity",
            "Unit_Price"
        ]
    )

    # Keep only records with positive quantities and prices.
    data = data[
        (data["Quantity"] > 0)
        & (data["Unit_Price"] > 0)
    ]

    print(f"Duplicate records removed: {duplicates_removed}")
    print(f"Records available after cleaning: {len(data)}")

    return data


def display_dataset_summary(data):
    """
    Display a basic summary of the cleaned dataset.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        None.
    """
    print("\n" + "=" * 60)
    print("DATASET SUMMARY")
    print("=" * 60)

    print(f"Number of records: {len(data)}")
    print(f"Number of columns: {len(data.columns)}")

    print("\nColumns:")
    for column in data.columns:
        print(f"- {column}")

    print("\nFirst five records:")
    print(data.head().to_string(index=False))

    print("\nData types:")
    print(data.dtypes)


def calculate_total_revenue(data):
    """
    Calculate the total revenue generated by all analyzed orders.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        The total revenue as a floating-point number.
    """
    total_revenue = data["Revenue"].sum()
    return total_revenue


def calculate_total_units(data):
    """
    Calculate the total number of units sold.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        The total number of units.
    """
    total_units = data["Quantity"].sum()
    return total_units


def analyze_categories(data):
    """
    Analyze revenue by product category.

    The data is grouped by Product_Category and revenue is
    aggregated with sum(). The result is then sorted from
    highest revenue to lowest revenue.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        A DataFrame containing category revenue results.
    """
    print("\n" + "=" * 60)
    print("QUESTION 1")
    print("Which product categories generate the most revenue?")
    print("=" * 60)

    category_analysis = (
        data.groupby("Product_Category")
        .agg(
            total_revenue=("Revenue", "sum"),
            total_units=("Quantity", "sum"),
            number_of_orders=("Order_ID", "count")
        )
        .sort_values(
            by="total_revenue",
            ascending=False
        )
    )

    print(
        category_analysis.to_string(
            formatters={
                "total_revenue": "${:,.2f}".format
            }
        )
    )

    return category_analysis


def analyze_regions(data):
    """
    Analyze average order value by geographic region.

    The program groups records by region and calculates both
    total revenue and average order value. The results are
    sorted by average order value.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        A DataFrame containing regional analysis results.
    """
    print("\n" + "=" * 60)
    print("QUESTION 2")
    print("Which regions have the highest average order value?")
    print("=" * 60)

    region_analysis = (
        data.groupby("Region")
        .agg(
            total_revenue=("Revenue", "sum"),
            average_order_value=("Revenue", "mean"),
            total_units=("Quantity", "sum"),
            number_of_orders=("Order_ID", "count")
        )
        .sort_values(
            by="average_order_value",
            ascending=False
        )
    )

    print(
        region_analysis.to_string(
            formatters={
                "total_revenue": "${:,.2f}".format,
                "average_order_value": "${:,.2f}".format
            }
        )
    )

    return region_analysis


def analyze_products(data):
    """
    Analyze the number of units sold by individual product.

    Products are grouped together and their quantities are
    summed. The result is sorted from the most units sold
    to the fewest.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        A DataFrame containing product sales results.
    """
    print("\n" + "=" * 60)
    print("QUESTION 3")
    print("Which products have the highest number of units sold?")
    print("=" * 60)

    product_analysis = (
        data.groupby("Product_Name")
        .agg(
            total_units=("Quantity", "sum"),
            total_revenue=("Revenue", "sum"),
            number_of_orders=("Order_ID", "count")
        )
        .sort_values(
            by="total_units",
            ascending=False
        )
    )

    top_products = product_analysis.head(10)

    print(
        top_products.to_string(
            formatters={
                "total_revenue": "${:,.2f}".format
            }
        )
    )

    return product_analysis


def demonstrate_filtering(data):
    """
    Demonstrate filtering by selecting orders above the
    average order revenue.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        A DataFrame containing above-average orders.
    """
    average_revenue = data["Revenue"].mean()

    filtered_data = data[
        data["Revenue"] > average_revenue
    ]

    print("\n" + "=" * 60)
    print("FILTERING DEMONSTRATION")
    print("=" * 60)

    print(f"Average order revenue: ${average_revenue:,.2f}")
    print(
        f"Orders above the average: {len(filtered_data)}"
    )

    return filtered_data


def demonstrate_date_conversion(data):
    """
    Demonstrate date conversion and extraction.

    The function creates a Year column from the converted
    Order_Date column and calculates yearly revenue.

    Args:
        data: The cleaned Pandas DataFrame.

    Returns:
        A DataFrame containing yearly revenue.
    """
    print("\n" + "=" * 60)
    print("DATE CONVERSION DEMONSTRATION")
    print("=" * 60)

    converted_data = data.copy()

    converted_data["Year"] = (
        converted_data["Order_Date"].dt.year
    )

    yearly_revenue = (
        converted_data.groupby("Year")
        .agg(
            total_revenue=("Revenue", "sum"),
            total_units=("Quantity", "sum")
        )
        .sort_index()
    )

    print(
        yearly_revenue.to_string(
            formatters={
                "total_revenue": "${:,.2f}".format
            }
        )
    )

    return yearly_revenue


def create_category_chart(category_analysis):
    """
    Create and save a bar chart showing revenue by category.

    Args:
        category_analysis: DataFrame containing category
                           revenue results.

    Returns:
        None.
    """
    print("\nCreating category revenue chart...")

    os.makedirs(OUTPUT_DIRECTORY, exist_ok=True)

    chart_data = category_analysis.sort_values(
        by="total_revenue",
        ascending=True
    )

    plt.figure(figsize=(10, 6))

    plt.barh(
        chart_data.index,
        chart_data["total_revenue"],
        color="steelblue"
    )

    plt.title("Revenue by Product Category")
    plt.xlabel("Revenue (USD)")
    plt.ylabel("Product Category")

    plt.tight_layout()

    plt.savefig(CHART_FILE, dpi=150)

    print(f"Chart saved to: {CHART_FILE}")

    plt.show()


def display_final_results(
    data,
    category_analysis,
    region_analysis,
    product_analysis
):
    """
    Display the most important conclusions from the analysis.

    Args:
        data: The cleaned Pandas DataFrame.
        category_analysis: Category analysis results.
        region_analysis: Regional analysis results.
        product_analysis: Product analysis results.

    Returns:
        None.
    """
    total_revenue = calculate_total_revenue(data)
    total_units = calculate_total_units(data)

    top_category = category_analysis.index[0]
    top_category_revenue = category_analysis.iloc[0]["total_revenue"]

    top_region = region_analysis.index[0]
    top_region_average = (
        region_analysis.iloc[0]["average_order_value"]
    )

    top_product = product_analysis.index[0]
    top_product_units = product_analysis.iloc[0]["total_units"]

    print("\n" + "=" * 60)
    print("FINAL RESULTS")
    print("=" * 60)

    print(f"Total revenue: ${total_revenue:,.2f}")
    print(f"Total units sold: {total_units:,.0f}")

    print(
        f"\nHighest-revenue category: {top_category}"
    )
    print(
        f"Revenue from this category: "
        f"${top_category_revenue:,.2f}"
    )

    print(
        f"\nHighest average order value region: "
        f"{top_region}"
    )
    print(
        f"Average order value: "
        f"${top_region_average:,.2f}"
    )

    print(
        f"\nProduct with the most units sold: "
        f"{top_product}"
    )
    print(
        f"Units sold: {top_product_units:,.0f}"
    )


def main():
    """
    Run the complete e-commerce data analysis.

    This function coordinates loading, cleaning, analysis,
    filtering, date conversion, visualization, and final
    result reporting.
    """
    print("=" * 60)
    print("CSE 310 - E-COMMERCE SALES ANALYSIS")
    print("Python + Pandas")
    print("=" * 60)

    data = load_data(DATA_FILE)

    if data is None:
        return

    data = clean_data(data)

    if data.empty:
        print("Error: No usable data remains after cleaning.")
        return

    display_dataset_summary(data)

    category_analysis = analyze_categories(data)

    region_analysis = analyze_regions(data)

    product_analysis = analyze_products(data)

    demonstrate_filtering(data)

    demonstrate_date_conversion(data)

    create_category_chart(category_analysis)

    display_final_results(
        data,
        category_analysis,
        region_analysis,
        product_analysis
    )

    print("\nAnalysis completed successfully.")


if __name__ == "__main__":
    main()
